Function deliver/1 only terminates with explicit exception
